# Welcome to Jekyll!
#

# Site settings
title: The Brace Place
description: |
  Board Certified Specialist  
  In Orthodontics  
  Ages 8-25
  
  417-782-1500, 800-DOCTOR-J
  
  1505 W. 10 St., Suite A, Joplin, MO 63801
owner: The Brace Place # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: info@braceplace.biz
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.braceplace.biz" # the base hostname & protocol for your site
social:
  #twitter: #https://twitter.com/<username>
  #github: #https://github.com/<username>
  #linkedin-square: #https://linkedin.com/in/<username>
  #facebook-official: #https://facebook.com/<username>
  #google-plus-square: #https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
